
spring:
  application:
    name: shop
  datasource:
    url: jdbc:mysql://localhost:3306/onlineshopdb?createDatabaseIfNotExist=true
    username: root
    password: rootpass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: eshghishop@gmail.com
    password: zvqbpfgosjbuekwa
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
ir:
  shop:
    application:
      jwtSecret: mySuperSecretKeyForJwtTokenWhichShouldBeLongEnough
      jwtExpirationMs: 3600000
server:
  port: 8080
